version: '3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5438:5432"
    expose:
      - "5432"
    networks:
      - backend-network

  redis:
    image: "redis"
    ports:
      - "6380:6379"
    expose:
      - "6379"
    networks:
      - backend-network

  django-app:
    build:
      context: .
    image: django-app:latest
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: database
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

  celery-worker:
    build:
      context: .
    image: celery-worker:latest
    command: celery -A framework.celery worker --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - backend-network
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: database
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "True"
    cap_add:
      - SYS_NICE

  celery-beat:
    build:
      context: .
    image: celery-beat:latest
    command: celery -A framework.celery beat --loglevel=info
    depends_on:
      - redis
      - postgres
    networks:
      - backend-network
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: database
      DATABASE_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      DEBUG: "True"
    cap_add:
      - SYS_NICE

networks:
  backend-network:
    driver: bridge
