# Generated by Django 4.2.5 on 2024-02-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='emis_paid_on_time',
            field=models.IntegerField(default=0),
        ),
    ]
